#!/usr/bin/env bash
# Bash script transfers file from client to a server

if [[ $# -lt 3 ]]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

if [[ $# == 4 ]]
then
   scp -o "$1" "$2" "$3" "$4"
fi
