#!/usr/bin/env bash
# Bash script installs nginx and sets up curl to return Hello World

apt-get update
apt-get -y install nginx
echo "rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4i/$1 permanent;" >> /etc/nginx/nginx.conf
service nginx restart
