#!/usr/bin/env bash
# Bash script configures a new web server with nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "46i\add_header X-Served-By $HOSTNAME ;" /etc/nginx/sites-available/default
service nginx restart
