#!/usr/bin/env bash
# Bash script debugs container, allowing nginx installation

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled
service nginx restart
