#!/usr/bin/env bash
# Bash script debugs container, allowing nginx installation
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled
service nginx restart
kill "$(pgrep nginx | head -1)"
