#!/usr/bin/env bash
# Bash script loops 1 to 10, displays bad luck on 4th loop, good luck on the 8th and the others Best School

i=1

while [ $i -le 10 ]
do
  if [ $i == 4 ]
  then
      echo "bad luck"
      ((i++))
  elif [ $i == 8 ]
  then
      echo "good luck"
      ((i++))
  else
      echo "Best School"
      ((i++))
  fi
done
