#!/usr/bin/env bash
# Bash script displays different strings depending on iteration number

i=1

while [ $i -le 20 ]
do
  if [ $i == 4 ]
  then
      echo "$i"
      echo "bad luck from China"
      ((i++))
  elif [ $i == 9 ]
  then
      echo "$i"
      echo "bad luck from Japan"
      ((i++))
  elif [ $i == 17 ]
  then
      echo "$i"
      echo "bad luck from Italy"
      ((i++))
  else
      echo "$i"
      ((i++))
  fi
done
