#!/usr/bin/env bash
# Bash script runs nginx as an nginx user

sudo pkill apache2
sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
